# Generated by Django 3.2.13 on 2022-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquirydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_inquiry',
            name='geo_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
