# Generated by Django 3.2.13 on 2022-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquirydata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_inquiry',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='data_inquiry',
            name='lattitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_inquiry',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='data_inquiry',
            table='data_inquiry',
        ),
    ]
