# Generated by Django 3.2.13 on 2022-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquirydata', '0002_auto_20220603_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_inquiry',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_inquiry',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
