# Generated by Django 3.2.13 on 2022-08-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquirydata', '0004_auto_20220607_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_inquiry',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='data_inquiry',
            name='existing_plant',
            field=models.BooleanField(null=True),
        ),
    ]
