# Generated by Django 3.2.13 on 2023-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='svuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Address Verified'),
        ),
    ]
