# Generated by Django 3.2.13 on 2023-04-15 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='phone number must be 10 digits long.', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('pin_code', models.CharField(max_length=6, verbose_name='Pin Code')),
                ('bill_amount', models.CharField(max_length=30, verbose_name='Bill Amount')),
            ],
        ),
    ]
